import type { AppSettings, ItemMetaMap } from '../../types.ts';

export const SETTINGS_KEY = 'tidal_web_settings';
export const TOKEN_KEY = 'tidal_web_token';
export const DEFAULT_TRACK_COUNT = 20;
export const DEFAULT_SHUFFLE_PLAYLIST = false;

export const SCOPES = [
  'user.read',
  'collection.read',
  'playlists.read',
  'playlists.write',
] as const;

export type JsonObject = Record<string, unknown>;

export type TokenState = {
  access_token: string;
  refresh_token?: string;
  expires_in?: number;
  expires_at: number;
} & JsonObject;

export function asObject(value: unknown): JsonObject | null {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as JsonObject) : null;
}

export function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

export function unixNow(): number {
  return Math.floor(Date.now() / 1000);
}

export function readJson<T>(key: string, fallback: T, storage: Storage = localStorage): T {
  try {
    const raw = storage.getItem(key);
    if (!raw) {
      return fallback;
    }
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function writeJson<T>(key: string, value: T, storage: Storage = localStorage): void {
  storage.setItem(key, JSON.stringify(value));
}

// Reads expiry from JWT payload only — no signature verification (intentional: browser has no key).
export function parseJwtExpiry(accessToken: string, expiresIn: unknown): number {
  try {
    const payload = accessToken.split('.')[1];
    const json = JSON.parse(
      atob(payload.replace(/-/g, '+').replace(/_/g, '/')),
    ) as JsonObject;
    if (typeof json.exp === 'number') {
      return json.exp;
    }
  } catch {
    // ignore
  }

  const parsed = Number(expiresIn ?? 3600);
  return unixNow() + (Number.isFinite(parsed) ? parsed : 3600);
}

export function normalizeTrackCount(
  value: unknown,
  fallback = DEFAULT_TRACK_COUNT,
): number {
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 1) {
    return fallback;
  }
  return parsed;
}

export function normalizeMeta(value: unknown): ItemMetaMap {
  if (!value || typeof value !== 'object') {
    return {};
  }
  const out: ItemMetaMap = {};
  for (const [id, meta] of Object.entries(value)) {
    if (!meta || typeof meta !== 'object') {
      continue;
    }
    const m = meta as { label?: unknown; subLabel?: unknown };
    out[String(id).toLowerCase()] = {
      label: String(m.label ?? ''),
      subLabel: String(m.subLabel ?? ''),
    };
  }
  return out;
}

export function defaultCountryCodeFromBrowser(): string {
  const fallback = 'US';

  if (typeof navigator === 'undefined') {
    return fallback;
  }

  const preferred = Array.isArray(navigator.languages) && navigator.languages.length > 0
    ? navigator.languages
    : [navigator.language];

  for (const tag of preferred) {
    try {
      const region = new Intl.Locale(String(tag ?? '')).region?.toUpperCase();
      if (region && /^[A-Z]{2}$/.test(region)) {
        return region;
      }
    } catch {
      // invalid tag — try next
    }
  }

  return fallback;
}

export function defaultSettingsState(): AppSettings {
  return {
    countryCode: defaultCountryCodeFromBrowser(),
    playlistName: 'My Artists Mix',
    playlistDescription: 'Generated by tidal-playlist-web',
    count: DEFAULT_TRACK_COUNT,
    shufflePlaylist: DEFAULT_SHUFFLE_PLAYLIST,
    includeLikedArtistsPool: true,
    includeLikedAlbumsPool: true,
    poolArtists: [],
    poolAlbums: [],
    blacklistedArtists: [],
    blacklistedAlbums: [],
    artistPoolMeta: {},
    artistBlacklistMeta: {},
    albumPoolMeta: {},
    albumBlacklistMeta: {},
  };
}
