import { signal } from '@lit-labs/signals';
import type { AppSettings, ItemMetaMap } from '../../types.ts';
import {
  DEFAULT_TRACK_COUNT,
  normalizeTrackCount,
} from '../tidal/shared.ts';
import type { TidalApi } from '../tidal/api.ts';
import { loadSettings, migrateRaw, saveSettings } from './persistence.ts';

/** Signal holding the current application settings; persisted on every update. */
export const settings = signal<AppSettings>(loadSettings());

/** Merges a partial patch into the settings signal and immediately persists. */
export function updateSettings(patch: Partial<AppSettings>): void {
  const next = { ...settings.get(), ...patch };
  settings.set(next);
  saveSettings(next);
}

function toIdArray(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.filter((v): v is string => typeof v === 'string' && v.trim() !== '').map((v) =>
      v.trim()
    );
  }
  return [];
}

/**
 * Validates and imports a raw unknown value as AppSettings.
 * Fetches artist/album metadata from the Tidal API to rebuild display labels.
 * Returns true on success; returns false if the raw value fails basic shape validation.
 */
export async function importSettings(raw: unknown, api: TidalApi): Promise<boolean> {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return false;
  }

  let obj = raw as Record<string, unknown>;
  // Unwrap old export format: { version, exportedAt, settings: { ... } }
  if (obj.settings && typeof obj.settings === 'object' && !Array.isArray(obj.settings)) {
    obj = obj.settings as Record<string, unknown>;
  }
  const source = migrateRaw(obj);
  const count = normalizeTrackCount(source.count ?? DEFAULT_TRACK_COUNT, NaN);

  if (!Number.isFinite(count)) {
    return false;
  }

  const poolArtists = toIdArray(source.poolArtists);
  const poolAlbums = toIdArray(source.poolAlbums);
  const blacklistedArtists = toIdArray(source.blacklistedArtists);
  const blacklistedAlbums = toIdArray(source.blacklistedAlbums);

  const [artistMeta, albumMeta] = await Promise.all([
    api.artistsByIds([...poolArtists, ...blacklistedArtists]),
    api.albumsByIds([...poolAlbums, ...blacklistedAlbums]),
  ]);

  const artistPoolMeta: ItemMetaMap = {};
  const artistBlacklistMeta: ItemMetaMap = {};
  for (const id of poolArtists) {
    if (artistMeta[id]) {
      artistPoolMeta[id] = artistMeta[id];
    }
  }
  for (const id of blacklistedArtists) {
    if (artistMeta[id]) {
      artistBlacklistMeta[id] = artistMeta[id];
    }
  }

  const albumPoolMeta: ItemMetaMap = {};
  const albumBlacklistMeta: ItemMetaMap = {};
  for (const id of poolAlbums) {
    if (albumMeta[id]) {
      albumPoolMeta[id] = albumMeta[id];
    }
  }
  for (const id of blacklistedAlbums) {
    if (albumMeta[id]) {
      albumBlacklistMeta[id] = albumMeta[id];
    }
  }

  const validated: AppSettings = {
    countryCode: String(source.countryCode ?? 'US').trim().toUpperCase() || 'US',
    playlistName: String(source.playlistName ?? 'My Artists Mix'),
    playlistDescription: String(source.playlistDescription ?? 'Generated by tidal-playlist-web'),
    count,
    shufflePlaylist: typeof source.shufflePlaylist === 'boolean' ? source.shufflePlaylist : false,
    includeLikedArtistsPool: Boolean(source.includeLikedArtistsPool ?? true),
    includeLikedAlbumsPool: Boolean(source.includeLikedAlbumsPool ?? true),
    poolArtists,
    poolAlbums,
    blacklistedArtists,
    blacklistedAlbums,
    artistPoolMeta,
    artistBlacklistMeta,
    albumPoolMeta,
    albumBlacklistMeta,
  };

  settings.set(validated);
  saveSettings(validated);
  return true;
}

/** Serialises the current settings to a pretty-printed JSON string, excluding derived meta. */
export function exportSettings(): string {
  const {
    artistPoolMeta: _artistPoolMeta,
    artistBlacklistMeta: _artistBlacklistMeta,
    albumPoolMeta: _albumPoolMeta,
    albumBlacklistMeta: _albumBlacklistMeta,
    ...rest
  } = settings.get();
  return JSON.stringify({ version: 1, ...rest }, null, 2);
}
