import { signal } from '@lit-labs/signals';
import type { AppSettings } from '../../types.ts';
import {
  DEFAULT_ALBUM_POOL_WEIGHT,
  DEFAULT_TRACK_COUNT,
  normalizeMeta,
  normalizeTrackCount,
} from '../tidal/shared.ts';
import { loadSettings, saveSettings } from './persistence.ts';

/** Signal holding the current application settings; persisted on every update. */
export const settings = signal<AppSettings>(loadSettings());

/** Merges a partial patch into the settings signal and immediately persists. */
export function updateSettings(patch: Partial<AppSettings>): void {
  const next = { ...settings.get(), ...patch };
  settings.set(next);
  saveSettings(next);
}

/**
 * Validates and imports a raw unknown value as AppSettings.
 * Returns true on success; returns false if the raw value fails basic shape validation.
 */
export function importSettings(raw: unknown): boolean {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) {
    return false;
  }

  const source = raw as Record<string, unknown>;
  const count = normalizeTrackCount(source.count ?? DEFAULT_TRACK_COUNT, NaN);

  if (!Number.isFinite(count)) {
    return false;
  }

  const rawAlbumPoolWeight = Number(source.albumPoolWeight ?? DEFAULT_ALBUM_POOL_WEIGHT);
  const albumPoolWeight = Number.isFinite(rawAlbumPoolWeight)
    ? Math.min(1, Math.max(0, rawAlbumPoolWeight))
    : DEFAULT_ALBUM_POOL_WEIGHT;

  const validated: AppSettings = {
    countryCode: String(source.countryCode ?? 'US')
      .trim()
      .toUpperCase() || 'US',
    playlistName: String(source.playlistName ?? 'My Artists Mix'),
    playlistDescription: String(
      source.playlistDescription ?? 'Generated by tidal-playlist-web',
    ),
    count,
    albumPoolWeight,
    shufflePlaylist: typeof source.shufflePlaylist === 'boolean' ? source.shufflePlaylist : false,
    includeLikedArtistsPool: Boolean(source.includeLikedArtistsPool ?? true),
    includeLikedAlbumsPool: Boolean(source.includeLikedAlbumsPool ?? true),
    poolArtists: String(source.poolArtists ?? source.whitelist ?? ''),
    poolAlbums: String(source.poolAlbums ?? source.albumWhitelist ?? ''),
    blacklist: String(source.blacklist ?? ''),
    albumBlacklist: String(source.albumBlacklist ?? ''),
    artistPoolMeta: normalizeMeta(source.artistPoolMeta ?? source.artistWhitelistMeta),
    artistBlacklistMeta: normalizeMeta(source.artistBlacklistMeta),
    albumPoolMeta: normalizeMeta(source.albumPoolMeta ?? source.albumWhitelistMeta),
    albumBlacklistMeta: normalizeMeta(source.albumBlacklistMeta),
  };

  settings.set(validated);
  saveSettings(validated);
  return true;
}

/** Serialises the current settings to a pretty-printed JSON string. */
export function exportSettings(): string {
  return JSON.stringify(settings.get(), null, 2);
}
