import type { AppSettings } from '../types.ts';
import { parseListField } from '../tidal/list-utils.ts';
import { loadSettings, saveSettings } from '../tidal/settings.ts';
import { DEFAULT_TRACK_COUNT, normalizeMeta, normalizeTrackCount } from '../tidal/shared.ts';

export type SettingsWidgets = {
  settingsForm: {
    setValues(values: AppSettings): void;
    getValues(): Pick<
      AppSettings,
      'countryCode' | 'playlistName' | 'playlistDescription' | 'count'
    >;
  };
  artistPool: {
    setItems(values: string[]): void;
    getItems(): string[];
    setItemMeta(meta: AppSettings['artistPoolMeta']): void;
    getItemMeta(): AppSettings['artistPoolMeta'];
  };
  artistBlacklist: {
    setItems(values: string[]): void;
    getItems(): string[];
    setItemMeta(meta: AppSettings['artistBlacklistMeta']): void;
    getItemMeta(): AppSettings['artistBlacklistMeta'];
  };
  albumPool: {
    setItems(values: string[]): void;
    getItems(): string[];
    setItemMeta(meta: AppSettings['albumPoolMeta']): void;
    getItemMeta(): AppSettings['albumPoolMeta'];
  };
  albumBlacklist: {
    setItems(values: string[]): void;
    getItems(): string[];
    setItemMeta(meta: AppSettings['albumBlacklistMeta']): void;
    getItemMeta(): AppSettings['albumBlacklistMeta'];
  };
  includeLikedArtistsPool: HTMLInputElement;
  includeLikedAlbumsPool: HTMLInputElement;
};

type SettingsPersistence = {
  load: () => AppSettings;
  save: (settings: AppSettings) => void;
};

export class AppSettingsStore {
  private settings: AppSettings;
  private saveTimer: number | null = null;
  private readonly debounceMs: number;
  private readonly persistence: SettingsPersistence;

  constructor(
    debounceMs = 300,
    persistence: SettingsPersistence = {
      load: () => loadSettings(),
      save: (settings) => saveSettings(settings),
    },
  ) {
    this.debounceMs = debounceMs;
    this.persistence = persistence;
    this.settings = this.persistence.load();
  }

  load(): AppSettings {
    this.settings = this.persistence.load();
    return this.settings;
  }

  getSettings(): AppSettings {
    return this.settings;
  }

  applyToUi(settings: AppSettings, widgets: SettingsWidgets): void {
    widgets.settingsForm.setValues(settings);
    widgets.artistPool.setItems(parseListField(settings.poolArtists));
    widgets.artistBlacklist.setItems(parseListField(settings.blacklist));
    widgets.albumPool.setItems(parseListField(settings.poolAlbums));
    widgets.albumBlacklist.setItems(parseListField(settings.albumBlacklist));
    widgets.includeLikedArtistsPool.checked = settings.includeLikedArtistsPool;
    widgets.includeLikedAlbumsPool.checked = settings.includeLikedAlbumsPool;
    widgets.artistPool.setItemMeta(settings.artistPoolMeta);
    widgets.artistBlacklist.setItemMeta(settings.artistBlacklistMeta);
    widgets.albumPool.setItemMeta(settings.albumPoolMeta);
    widgets.albumBlacklist.setItemMeta(settings.albumBlacklistMeta);
  }

  readFromUi(widgets: SettingsWidgets): AppSettings {
    const base = widgets.settingsForm.getValues();
    return {
      ...base,
      includeLikedArtistsPool: widgets.includeLikedArtistsPool.checked,
      includeLikedAlbumsPool: widgets.includeLikedAlbumsPool.checked,
      poolArtists: widgets.artistPool.getItems().join('\n'),
      poolAlbums: widgets.albumPool.getItems().join('\n'),
      blacklist: widgets.artistBlacklist.getItems().join('\n'),
      albumBlacklist: widgets.albumBlacklist.getItems().join('\n'),
      artistPoolMeta: widgets.artistPool.getItemMeta(),
      artistBlacklistMeta: widgets.artistBlacklist.getItemMeta(),
      albumPoolMeta: widgets.albumPool.getItemMeta(),
      albumBlacklistMeta: widgets.albumBlacklist.getItemMeta(),
    };
  }

  updateFromUiDebounced(widgets: SettingsWidgets): AppSettings {
    const next = this.readFromUi(widgets);
    this.settings = next;
    this.scheduleSave();
    return next;
  }

  updateFromUiImmediate(widgets: SettingsWidgets): AppSettings {
    const next = this.readFromUi(widgets);
    this.settings = next;
    this.saveNow();
    return next;
  }

  replace(next: AppSettings): AppSettings {
    this.settings = next;
    this.saveNow();
    return next;
  }

  flush(): void {
    if (this.saveTimer === null) {
      return;
    }
    clearTimeout(this.saveTimer);
    this.saveTimer = null;
    this.saveNow();
  }

  importSettings(raw: unknown): AppSettings {
    const source = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {};
    const count = normalizeTrackCount(source.count ?? DEFAULT_TRACK_COUNT, NaN);
    if (!Number.isFinite(count)) {
      throw new Error('Invalid config: "count" must be an integer greater than 0.');
    }

    return {
      countryCode: String(source.countryCode ?? 'US')
        .trim()
        .toUpperCase() || 'US',
      playlistName: String(source.playlistName ?? 'My Artists Mix'),
      playlistDescription: String(
        source.playlistDescription ?? 'Generated by tidal-playlist-web',
      ),
      count,
      includeLikedArtistsPool: Boolean(source.includeLikedArtistsPool ?? true),
      includeLikedAlbumsPool: Boolean(source.includeLikedAlbumsPool ?? true),
      poolArtists: String(source.poolArtists ?? source.whitelist ?? ''),
      poolAlbums: String(source.poolAlbums ?? source.albumWhitelist ?? ''),
      blacklist: String(source.blacklist ?? ''),
      albumBlacklist: String(source.albumBlacklist ?? ''),
      artistPoolMeta: normalizeMeta(source.artistPoolMeta ?? source.artistWhitelistMeta),
      artistBlacklistMeta: normalizeMeta(source.artistBlacklistMeta),
      albumPoolMeta: normalizeMeta(source.albumPoolMeta ?? source.albumWhitelistMeta),
      albumBlacklistMeta: normalizeMeta(source.albumBlacklistMeta),
    };
  }

  private scheduleSave(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
    }
    this.saveTimer = globalThis.setTimeout(() => {
      this.saveTimer = null;
      this.saveNow();
    }, this.debounceMs);
  }

  private saveNow(): void {
    this.persistence.save(this.settings);
  }
}
