import type { PlaylistSettingsFormValues } from '../types.ts';
import { defaultCountryCodeFromBrowser } from '../tidal/shared.ts';
import { ShadowComponent } from './shadow-component.ts';

const COUNTRY_CODES: string[] = [
  'AD',
  'AE',
  'AF',
  'AG',
  'AI',
  'AL',
  'AM',
  'AO',
  'AQ',
  'AR',
  'AS',
  'AT',
  'AU',
  'AW',
  'AX',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BF',
  'BG',
  'BH',
  'BI',
  'BJ',
  'BL',
  'BM',
  'BN',
  'BO',
  'BQ',
  'BR',
  'BS',
  'BT',
  'BV',
  'BW',
  'BY',
  'BZ',
  'CA',
  'CC',
  'CD',
  'CF',
  'CG',
  'CH',
  'CI',
  'CK',
  'CL',
  'CM',
  'CN',
  'CO',
  'CR',
  'CU',
  'CV',
  'CW',
  'CX',
  'CY',
  'CZ',
  'DE',
  'DJ',
  'DK',
  'DM',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'EH',
  'ER',
  'ES',
  'ET',
  'FI',
  'FJ',
  'FK',
  'FM',
  'FO',
  'FR',
  'GA',
  'GB',
  'GD',
  'GE',
  'GF',
  'GG',
  'GH',
  'GI',
  'GL',
  'GM',
  'GN',
  'GP',
  'GQ',
  'GR',
  'GS',
  'GT',
  'GU',
  'GW',
  'GY',
  'HK',
  'HM',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IM',
  'IN',
  'IO',
  'IQ',
  'IR',
  'IS',
  'IT',
  'JE',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KI',
  'KM',
  'KN',
  'KP',
  'KR',
  'KW',
  'KY',
  'KZ',
  'LA',
  'LB',
  'LC',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MF',
  'MG',
  'MH',
  'MK',
  'ML',
  'MM',
  'MN',
  'MO',
  'MP',
  'MQ',
  'MR',
  'MS',
  'MT',
  'MU',
  'MV',
  'MW',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NC',
  'NE',
  'NF',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NR',
  'NU',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PF',
  'PG',
  'PH',
  'PK',
  'PL',
  'PM',
  'PN',
  'PR',
  'PS',
  'PT',
  'PW',
  'PY',
  'QA',
  'RE',
  'RO',
  'RS',
  'RU',
  'RW',
  'SA',
  'SB',
  'SC',
  'SD',
  'SE',
  'SG',
  'SH',
  'SI',
  'SJ',
  'SK',
  'SL',
  'SM',
  'SN',
  'SO',
  'SR',
  'SS',
  'ST',
  'SV',
  'SX',
  'SY',
  'SZ',
  'TC',
  'TD',
  'TF',
  'TG',
  'TH',
  'TJ',
  'TK',
  'TL',
  'TM',
  'TN',
  'TO',
  'TR',
  'TT',
  'TV',
  'TW',
  'TZ',
  'UA',
  'UG',
  'UM',
  'US',
  'UY',
  'UZ',
  'VA',
  'VC',
  'VE',
  'VG',
  'VI',
  'VN',
  'VU',
  'WF',
  'WS',
  'YE',
  'YT',
  'ZA',
  'ZM',
  'ZW',
];

const COUNTRY_NAME_DISPLAY = typeof Intl.DisplayNames === 'function'
  ? new Intl.DisplayNames(['en'], { type: 'region' })
  : null;

function renderCountryOptions(selectedValue: string): string {
  const selected = String(selectedValue || 'US').toUpperCase();
  const options = [...COUNTRY_CODES];
  if (!options.includes(selected)) {
    options.unshift(selected);
  }

  return options
    .map((code) => {
      const name = COUNTRY_NAME_DISPLAY?.of(code);
      const label = name ? `${name} (${code})` : code;
      const selectedAttr = code === selected ? ' selected' : '';
      return `<option value="${code}"${selectedAttr}>${label}</option>`;
    })
    .join('');
}

export class PlaylistSettings extends ShadowComponent {
  connectedCallback(): void {
    this.render();
  }

  private render(values: Partial<PlaylistSettingsFormValues> = {}): void {
    const countryCode = values.countryCode ?? defaultCountryCodeFromBrowser();
    const playlistName = values.playlistName ?? 'My Artists Mix';
    const playlistDescription = values.playlistDescription ?? 'Generated by tidal-playlist-web';
    const count = Number.isFinite(values.count) ? values.count : 25;

    this.renderShadow(
      `
      <label>Country code (ISO 3166-1 alpha-2)
        <select id="country-code">${renderCountryOptions(countryCode)}</select>
      </label>

      <label>Playlist name
        <input id="playlist-name" value="${playlistName}" />
      </label>

      <label>Playlist description
        <input id="playlist-description" value="${playlistDescription}" />
      </label>

      <label>Track count
        <input id="count" type="number" min="1" value="${count}" />
      </label>
    `,
      `
        :host {
          display: grid;
          gap: 0.75rem;
        }
        label {
          display: flex;
          flex-direction: column;
          gap: 0.35rem;
          padding: 0.65rem;
          border-radius: 8px;
          border: 1px solid var(--line, #d9dde3);
          background: var(--panel, #fff);
          font-size: 0.93rem;
        }
        input,
        select {
          box-sizing: border-box;
          width: 100%;
          padding: 0.5rem 0.6rem;
        }
      `,
    );
  }

  setValues(values: Partial<PlaylistSettingsFormValues>): void {
    this.render(values);
  }

  getValues(): PlaylistSettingsFormValues {
    const countryCodeInput = this.requireElement<HTMLSelectElement>(
      '#country-code',
    );
    const playlistNameInput = this.requireElement<HTMLInputElement>(
      '#playlist-name',
    );
    const playlistDescriptionInput = this.requireElement<HTMLInputElement>(
      '#playlist-description',
    );
    const countInput = this.requireElement<HTMLInputElement>('#count');

    return {
      countryCode: countryCodeInput.value.trim().toUpperCase() || 'US',
      playlistName: playlistNameInput.value.trim(),
      playlistDescription: playlistDescriptionInput.value.trim(),
      count: Number(countInput.value),
    };
  }
}

customElements.define('playlist-settings', PlaylistSettings);
