import { css, html, nothing } from 'lit';
import { customElement, query, state } from 'lit/decorators.js';
import { StyledElement } from '../styled-element.ts';
import type { PlaylistSettingsFormValues } from '../types.ts';
import { defaultCountryCodeFromBrowser } from '../modules/tidal/shared.ts';

const COUNTRY_CODES: string[] = [
  'AD',
  'AE',
  'AF',
  'AG',
  'AI',
  'AL',
  'AM',
  'AO',
  'AQ',
  'AR',
  'AS',
  'AT',
  'AU',
  'AW',
  'AX',
  'AZ',
  'BA',
  'BB',
  'BD',
  'BE',
  'BF',
  'BG',
  'BH',
  'BI',
  'BJ',
  'BL',
  'BM',
  'BN',
  'BO',
  'BQ',
  'BR',
  'BS',
  'BT',
  'BV',
  'BW',
  'BY',
  'BZ',
  'CA',
  'CC',
  'CD',
  'CF',
  'CG',
  'CH',
  'CI',
  'CK',
  'CL',
  'CM',
  'CN',
  'CO',
  'CR',
  'CU',
  'CV',
  'CW',
  'CX',
  'CY',
  'CZ',
  'DE',
  'DJ',
  'DK',
  'DM',
  'DO',
  'DZ',
  'EC',
  'EE',
  'EG',
  'EH',
  'ER',
  'ES',
  'ET',
  'FI',
  'FJ',
  'FK',
  'FM',
  'FO',
  'FR',
  'GA',
  'GB',
  'GD',
  'GE',
  'GF',
  'GG',
  'GH',
  'GI',
  'GL',
  'GM',
  'GN',
  'GP',
  'GQ',
  'GR',
  'GS',
  'GT',
  'GU',
  'GW',
  'GY',
  'HK',
  'HM',
  'HN',
  'HR',
  'HT',
  'HU',
  'ID',
  'IE',
  'IL',
  'IM',
  'IN',
  'IO',
  'IQ',
  'IR',
  'IS',
  'IT',
  'JE',
  'JM',
  'JO',
  'JP',
  'KE',
  'KG',
  'KH',
  'KI',
  'KM',
  'KN',
  'KP',
  'KR',
  'KW',
  'KY',
  'KZ',
  'LA',
  'LB',
  'LC',
  'LI',
  'LK',
  'LR',
  'LS',
  'LT',
  'LU',
  'LV',
  'LY',
  'MA',
  'MC',
  'MD',
  'ME',
  'MF',
  'MG',
  'MH',
  'MK',
  'ML',
  'MM',
  'MN',
  'MO',
  'MP',
  'MQ',
  'MR',
  'MS',
  'MT',
  'MU',
  'MV',
  'MW',
  'MX',
  'MY',
  'MZ',
  'NA',
  'NC',
  'NE',
  'NF',
  'NG',
  'NI',
  'NL',
  'NO',
  'NP',
  'NR',
  'NU',
  'NZ',
  'OM',
  'PA',
  'PE',
  'PF',
  'PG',
  'PH',
  'PK',
  'PL',
  'PM',
  'PN',
  'PR',
  'PS',
  'PT',
  'PW',
  'PY',
  'QA',
  'RE',
  'RO',
  'RS',
  'RU',
  'RW',
  'SA',
  'SB',
  'SC',
  'SD',
  'SE',
  'SG',
  'SH',
  'SI',
  'SJ',
  'SK',
  'SL',
  'SM',
  'SN',
  'SO',
  'SR',
  'SS',
  'ST',
  'SV',
  'SX',
  'SY',
  'SZ',
  'TC',
  'TD',
  'TF',
  'TG',
  'TH',
  'TJ',
  'TK',
  'TL',
  'TM',
  'TN',
  'TO',
  'TR',
  'TT',
  'TV',
  'TW',
  'TZ',
  'UA',
  'UG',
  'UM',
  'US',
  'UY',
  'UZ',
  'VA',
  'VC',
  'VE',
  'VG',
  'VI',
  'VN',
  'VU',
  'WF',
  'WS',
  'YE',
  'YT',
  'ZA',
  'ZM',
  'ZW',
];

const COUNTRY_NAME_DISPLAY = typeof Intl.DisplayNames === 'function'
  ? new Intl.DisplayNames(['en'], { type: 'region' })
  : null;

@customElement('playlist-settings')
export class PlaylistSettings extends StyledElement {
  @state()
  private values: PlaylistSettingsFormValues = {
    countryCode: defaultCountryCodeFromBrowser(),
    playlistName: 'My Artists Mix',
    playlistDescription: 'Generated by tidal-playlist-web',
    count: 25,
    albumPoolWeight: 0.2,
    shufflePlaylist: false,
  };

  @query('#country-code')
  private countryCodeEl!: HTMLSelectElement;

  @query('#playlist-name')
  private playlistNameEl!: HTMLInputElement;

  @query('#playlist-description')
  private playlistDescriptionEl!: HTMLTextAreaElement;

  @query('#count')
  private countEl!: HTMLInputElement;

  @query('#album-pool-weight')
  private albumPoolWeightEl!: HTMLInputElement;

  @query('#shuffle-playlist')
  private shufflePlaylistEl!: HTMLInputElement;

  static override localStyles = css`
    :host {
      display: block;
    }
    .settings-grid {
      display: grid;
      grid-template-columns: 1fr;
      gap: 0.65rem;
    }
    label:not(.shuffle-toggle) {
      display: flex;
      flex-direction: column;
      gap: 0.35rem;
      padding: 0.65rem;
      border-radius: 8px;
      border: 1px solid var(--line, #d9dde3);
      background: var(--panel, #fff);
      font-size: 0.93rem;
    }
    input[type="text"],
    input[type="number"],
    select,
    textarea {
      box-sizing: border-box;
      width: 100%;
      padding: 0.5rem 0.6rem;
    }
    textarea {
      min-height: 4rem;
      resize: vertical;
      font-family: inherit;
    }
    .shuffle-toggle {
      display: flex;
      flex-direction: row;
      align-items: center;
      gap: 0.5rem;
      font-size: 0.93rem;
      margin-top: 0.6rem;
      padding: 0;
      border: none;
      background: none;
    }
    input[type="checkbox"] {
      width: auto;
      cursor: pointer;
    }
  `;

  override render() {
    const {
      countryCode,
      playlistName,
      playlistDescription,
      count,
      albumPoolWeight,
      shufflePlaylist,
    } = this.values;

    const selected = String(countryCode || 'US').toUpperCase();
    const codes = [...COUNTRY_CODES];
    if (!codes.includes(selected)) {
      codes.unshift(selected);
    }

    return html`
      <div class="settings-grid">
        <label>
          Country code (ISO 3166-1 alpha-2)
          <select id="country-code">
            ${codes.map((code) => {
              const name = COUNTRY_NAME_DISPLAY?.of(code);
              const label = name ? `${name} (${code})` : code;
              return html`
                <option value="${code}" ?selected="${code === selected}">${label}</option>
              `;
            })}
          </select>
        </label>

        <label>
          Playlist name
          <input id="playlist-name" type="text" .value="${playlistName}" />
        </label>

        <label>
          Playlist description
          <textarea id="playlist-description" .value="${playlistDescription}"></textarea>
        </label>

        <label>
          Track count
          <input id="count" type="number" min="1" .value="${String(count)}" />
        </label>

        <label>
          (experimental) Album pool weight (0 = artists only, 1 = albums only)
          <input
            id="album-pool-weight"
            type="number"
            min="0"
            max="1"
            step="0.05"
            .value="${String(albumPoolWeight)}"
          />
        </label>

        <label class="shuffle-toggle">
          <input id="shuffle-playlist" type="checkbox" .checked="${shufflePlaylist}" />
          Shuffle playlist after build
        </label>
      </div>
    `;
  }

  // ---------- public API ----------

  setValues(values: Partial<PlaylistSettingsFormValues>): void {
    this.values = { ...this.values, ...values };
  }

  getValues(): PlaylistSettingsFormValues {
    return {
      countryCode: this.countryCodeEl.value.trim().toUpperCase() || 'US',
      playlistName: this.playlistNameEl.value.trim(),
      playlistDescription: this.playlistDescriptionEl.value.trim(),
      count: Number(this.countEl.value),
      albumPoolWeight: Number(this.albumPoolWeightEl.value),
      shufflePlaylist: this.shufflePlaylistEl.checked,
    };
  }
}

// nothing imported for template consistency with other components
void nothing;

declare global {
  interface HTMLElementTagNameMap {
    'playlist-settings': PlaylistSettings;
  }
}
